### PR TITLE
Task 3

### PR DESCRIPTION
**Pull request by Nikitozz13**
Finished TASK-3 with additional tasks:
async/await, ES6 modules, custom Webpack settings, Swagger, unit tests, basic error handling

- S3 link (403): https://awsreactaplsless2.s3.eu-west-2.amazonaws.com
- CloudFront link: https://djli799ppaabs.cloudfront.net/
- FrontEnd repository: https://github.com/Nikitozz13/shop-react-redux-cloudfront
- FE pull request to support API: https://github.com/Nikitozz13/shop-react-redux-cloudfront/pull/2
- Swagger: https://flw23890r2.execute-api.eu-west-2.amazonaws.com/dev/swagger
- /products api: https://flw23890r2.execute-api.eu-west-2.amazonaws.com/dev/products
- /products/{productId} api: https://flw23890r2.execute-api.eu-west-2.amazonaws.com/dev/products/2

### CODE REVIEW

**Comment by Nikitozz13** [comment]
Have finished with unit tests, I guess everything is completed

**Comment by artsiomshushkevich** [comment]
Some small notes:

 - swagger folder can be added to gitignore
 - product not found should return 404 response
 - currently API returns data not from mocks, but I guess, from DB of task 4, I suggest for such cases using different region for new tasks in order to not overwrite older APIs
 - also you can use middy middleware to set up cors

**Comment by Nikitozz13** [comment]
@artsiomshushkevich Thank you for your effort! Great advices, will try to implement these in the task here, though it will require some appropriate changes as I also have implemented response code setting for task-4.

**Comment by Nikitozz13** [comment]
@artsiomshushkevich have updated code with your comments. Also here is endpoints for that task based on another AWS region:

  GET - https://5er6vm6n04.execute-api.eu-west-1.amazonaws.com/dev/products
  GET - https://5er6vm6n04.execute-api.eu-west-1.amazonaws.com/dev/products/{productId}
  GET - https://5er6vm6n04.execute-api.eu-west-1.amazonaws.com/dev/swagger
  GET - https://5er6vm6n04.execute-api.eu-west-1.amazonaws.com/dev/swagger.json

But it could not work in FE as I have another region usage there

**Pull request merged**
